version: "3.8"

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../task_management_ui:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongo-data:
